// <auto-generated />
namespace Sudoku.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedSaveGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSaveGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201402130953329_addedSaveGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
