// <auto-generated />
namespace Sudoku.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedDifficultyToBoard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDifficultyToBoard));
        
        string IMigrationMetadata.Id
        {
            get { return "201402041549527_addedDifficultyToBoard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
