// <auto-generated />
namespace Sudoku.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixedRatingsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedRatingsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201404220911033_fixedRatingsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
