// <auto-generated />
namespace Sudoku.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedRatings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedRatings));
        
        string IMigrationMetadata.Id
        {
            get { return "201402050928078_addedRatings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
