// <auto-generated />
namespace Sudoku.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixedUserProfileSavedGamesRelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedUserProfileSavedGamesRelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201402131038483_fixedUserProfileSavedGamesRelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
